### ISSUE TITLE
Changed ID?

### ISSUE THREAD

**Issue by joaomoreno** [eamodio/vscode-tsl-problem-matcher#10]
The Marketplace tells me `amodio.tsl-problem-matcher` is the new ID for this extension. Is this correct?

**Comment by alefragnani** [comment]
It seems all extensions were updated, except GitLens (which now shows as GitKraken).

**Comment by alefragnani** [comment]
@eamodio I suppose the `publisher` difference may be the reason why `Project Details` section remains empty on your other extensions.

**Comment by eamodio** [comment]
@alefragnani Ah, apparently -- seems to get fixed when I publish an updated version with the new id.

**Comment by felipecrs** [comment]
Also, I will be deprecating my fork in favor of this one again. Thank you.
