### ISSUE TITLE
Errors from webpack not showing in problems pane

### ISSUE THREAD

**Issue by junalmeida** [eamodio/vscode-tsl-problem-matcher#3]
- TypeScript + Webpack Problem Matchers Version: 0.3.1
- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:

When using this combination:
1. webpack - 4.44.2 (`--watch --info-verbosity verbose`)
2. typescript - 3.7.5
3. ts-loader: 8.0.4
4. fork-ts-checker-webpack-plugin - 5.2.0 (formatter type = basic) 
5. The following problem matches: 
```
                "$ts-webpack-watch",
                "$ts-checker-webpack-watch",
                "$ts-checker-eslint-webpack-watch",
                "$sass-loader",
```

I can't see compiler messages in problems pane, and yet I have 5 compilation errors of type TS2339 and TS2307

**Comment by eamodio** [comment]
Should be resolved in 0.5.0.
