### ISSUE TITLE
Extension causes vs code's to (ofc infinitally) wait for build watch task

### ISSUE THREAD

**Issue by mcpiroman** [eamodio/vscode-tsl-problem-matcher#6]
- TypeScript + Webpack Problem Matchers Version: v0.3.1
  
- VSCode Version: 1.53.2
- OS Version:  Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create new VS Code extension with webpack
2. Start the `Run Extension` debug task (hit F5)

**Comment by doug-shontz** [comment]
Same problem here but on Mac Big Sur 11.2.1.  Same extension and VSCode version.  Removing the eamodio problem matchers from tasks.json and the eamodio recommendations from extension.json bypasses the issue.
